// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvcEwvy81QK-hL2xYeARQH-XurdV8G_YM',
    appId: '1:778080616435:web:eb31dfcdda2c9d3ad6dc86',
    messagingSenderId: '778080616435',
    projectId: 'luar-sekolah-lms-4bdee',
    authDomain: 'luar-sekolah-lms-4bdee.firebaseapp.com',
    storageBucket: 'luar-sekolah-lms-4bdee.firebasestorage.app',
    measurementId: 'G-R73TFXLQZV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnou5tqasswKNdu9mjfHDFT2nlhkbXcQU',
    appId: '1:778080616435:android:140eb773daaa8deed6dc86',
    messagingSenderId: '778080616435',
    projectId: 'luar-sekolah-lms-4bdee',
    storageBucket: 'luar-sekolah-lms-4bdee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpuC6gM0R-WThf-DGCE8IkDU_3F0JDEEA',
    appId: '1:778080616435:ios:866164672a79f99ad6dc86',
    messagingSenderId: '778080616435',
    projectId: 'luar-sekolah-lms-4bdee',
    storageBucket: 'luar-sekolah-lms-4bdee.firebasestorage.app',
    iosBundleId: 'com.example.luarSekolahLms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpuC6gM0R-WThf-DGCE8IkDU_3F0JDEEA',
    appId: '1:778080616435:ios:866164672a79f99ad6dc86',
    messagingSenderId: '778080616435',
    projectId: 'luar-sekolah-lms-4bdee',
    storageBucket: 'luar-sekolah-lms-4bdee.firebasestorage.app',
    iosBundleId: 'com.example.luarSekolahLms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvcEwvy81QK-hL2xYeARQH-XurdV8G_YM',
    appId: '1:778080616435:web:9c9a947903012127d6dc86',
    messagingSenderId: '778080616435',
    projectId: 'luar-sekolah-lms-4bdee',
    authDomain: 'luar-sekolah-lms-4bdee.firebaseapp.com',
    storageBucket: 'luar-sekolah-lms-4bdee.firebasestorage.app',
    measurementId: 'G-PB80E03CQE',
  );
}
